set(CC_USE_GLES3 ON)
set(CC_USE_GLES2 ON)
set(APP_NAME cx3-so)
set(COCOS_X_PATH "/Applications/CocosCreator/Creator/3.1.1/CocosCreator.app/Contents/Resources/resources/3d/engine-native")
set(CC_USE_VULKAN OFF)
set(USE_PHYSICS_PHYSX OFF)
set(USE_AUDIO ON)
set(USE_VIDEO ON)
set(USE_WEBVIEW ON)
set(USE_SPINE OFF)
set(USE_DRAGONBONES ON)
set(USE_JOB_SYSTEM_TBB ON)

